# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.levelLabel = QtWidgets.QLabel(self.centralwidget)
        self.levelLabel.setGeometry(QtCore.QRect(570, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.levelLabel.setFont(font)
        self.levelLabel.setObjectName("levelLabel")
        self.levelSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.levelSpinBox.setGeometry(QtCore.QRect(710, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.levelSpinBox.setFont(font)
        self.levelSpinBox.setMinimum(1)
        self.levelSpinBox.setMaximum(2)
        self.levelSpinBox.setObjectName("levelSpinBox")
        self.gamePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.gamePushButton.setGeometry(QtCore.QRect(780, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.gamePushButton.setFont(font)
        self.gamePushButton.setObjectName("gamePushButton")
        self.newGamePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGamePushButton.setGeometry(QtCore.QRect(750, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.newGamePushButton.setFont(font)
        self.newGamePushButton.setObjectName("newGamePushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 512, 512))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gameFieldTableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.gameFieldTableView.horizontalHeader().setVisible(False)
        self.gameFieldTableView.verticalHeader().setVisible(False)
        self.gameFieldTableView.horizontalHeader().setDefaultSectionSize(85)
        self.gameFieldTableView.verticalHeader().setDefaultSectionSize(85)
        self.gameFieldTableView.setObjectName("gameFieldTableView")
        self.verticalLayout_2.addWidget(self.gameFieldTableView)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(560, 80, 341, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(560, 410, 341, 110))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.exitGamePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitGamePushButton.setGeometry(QtCore.QRect(560, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exitGamePushButton.setFont(font)
        self.exitGamePushButton.setObjectName("exitGamePushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.levelLabel.setText(_translate("MainWindow", "УРОВЕНЬ:"))
        self.gamePushButton.setText(_translate("MainWindow", "ИГРАТЬ"))
        self.newGamePushButton.setText(_translate("MainWindow", "Обновить"))
        self.textBrowser.setMarkdown(_translate("MainWindow", "**Задача**: загнать цветные шарики в свои ворота соответствующего цвета. \n"
"\n"
"**Управление**: нажать левой кнопкой мыши на шарик, правой кнопкой мыши выбрать\n"
"направление (по диагонали шарик не летает), шарик летит до упора.\n"
"\n"
""))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Задача</span>: загнать цветные шарики в свои ворота соответствующего цвета. </p>\n"
"<p style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Управление</span>: нажать левой кнопкой мыши на шарик, правой кнопкой мыши выбрать направление (по диагонали шарик не летает), шарик летит до упора.</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Связь с автором</span><span style=\" font-size:16pt;\">: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">zhdanova@gmail.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">https://vk.com/quiet_mip</span></p></body></html>"))
        self.exitGamePushButton.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
